name: Deploy Backend to Production Server

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy backend" to confirm overwriting prod with main and triggering deployment'
        required: true
        default: ""

jobs:
  deploy:
    if: ${{ github.event.inputs.confirm == 'deploy backend' }}
    runs-on: [self-hosted, prod-runner]

    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.PAT_FOR_ACTIONS }}
          fetch-depth: 0
          persist-credentials: true

      - name: Mark Git directory as safe
        run: git config --global --add safe.directory /home/github-runner/monolithic

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Force-reset prod to main (no merge commits)
        run: |
          git fetch origin
          git checkout prod
          git reset --hard origin/main
          git push origin prod --force

      - name: Deploy updated prod
        run: |
          cd /home/github-runner/monolithic
          git pull origin prod
          docker-compose down
          docker-compose up -d --build
