name: Deploy Frontend to Cloudflare Pages

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "deploy frontend" to confirm deploying the frontend from prod branch'
        required: true
        default: ""

jobs:
  deploy-frontend:
    if: ${{ github.event.inputs.confirm == 'deploy frontend' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout frontend from prod
        uses: actions/checkout@v3
        with:
          ref: prod

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: vite-frontend/package-lock.json

      - name: Inject VITE_ secrets into .env
        working-directory: vite-frontend
        run: |
          echo "VITE_HCAPTCHA_SITEKEY=${{ secrets.VITE_HCAPTCHA_SITEKEY }}" >> .env
          echo "VITE_GOOGLE_CLIENT_ID=${{ secrets.VITE_GOOGLE_CLIENT_ID }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "VITE_GITHUB_APP_CLIENT_ID=${{ secrets.VITE_GITHUB_APP_CLIENT_ID }}" >> .env
          echo "VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }}" >> .env

      - name: Upgrade Keyrune
        working-directory: vite-frontend
        run: |
          npm install keyrune@latest --save

      - name: Install dependencies & build
        working-directory: vite-frontend
        run: |
          npm install
          npm run build

      - name: Install wrangler
        run: npm install -g wrangler

      - name: Deploy to Cloudflare Pages (production)
        run: |
          wrangler pages deploy vite-frontend/dist \
            --project-name=mtgscan-cards \
            --branch=prod
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}